
## Harpia build configs

language: php
dist: trusty
sudo: required

php:
  - 7.1

before_script:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get -qq update
  - sudo apt-get install -y php7.1-memcached
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction >> /dev/null

script:
  - ./bin/phpunit -c phpunit.xml