
## Harpia build configs

language: php
dist: trusty
sudo: required

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  -  ./bin/paratest -p4 --phpunit ./bin/phpunit --configuration phpunit.xml